### ISSUE TITLE
remote name not able to resolve

### ISSUE THREAD

**Issue by KushJoshi** [tableau/TabMigrate#30]
Hello,

when we are trying to do TabMigrate testing, we are getting following error.

Error: Error sending sign in request: System.Net.WebException: The remote name could not be resolved: 'myserver.com'
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at TableauServerRequestBase.SendHttpRequestContents_Inner(WebRequest request, String bodyText, String httpMethod)
   at TableauServerRequestBase.SendPostContents(WebRequest request, String bodyText)
   at TableauServerSignIn.ExecuteRequest()

Does any body knows what can be done, we are trying to migrate sites from one server to another and we are connected via VPN.

Thanks in advance for your support.

**Comment by slewt** [comment]
all boils down to your DNS configuration, looks like you are trying to use a domain name to reference your Tableau Server that your local computer cannot get an answer for.
