### ISSUE TITLE
Uploading Workbooks with Live Connections failing

### ISSUE THREAD

**Issue by sdasgupta-18** [tableau/TabMigrate#31]
I exported some workbooks and data sources which have Live connections to HANA databases. When I try to "upload" these workbooks & data sources to a target server, I get the below errors:

"....Possibly the workbook contains live database connections that need credentials so that thumbnail images can get generated....."

Does this mean, we cannot upload workbooks with Live connections to data sources?

**Comment by sdasgupta-18** [comment]
Thanks! So we are saying, if there are 100 workbooks then we have to include <credential> tags 100 times in the xml file, right?
Where do I need to select the xml file in the interface for "Upload option"?

**Comment by rferraton** [comment]
If you have embeded datasources yes, but if you have "shared" datasources, only for each "shared" datasources.

The xml file is defined here : 
![image](https://user-images.githubusercontent.com/16419423/40505991-44b91e0e-5f96-11e8-96bd-fb443addaae2.png)

**Comment by sdasgupta-18** [comment]
Hi, I have a workbook that connects to a SQL server database using a user-id and password. I created the XML file (WBs.xml) as below & kept it in c drive. 

![image](https://user-images.githubusercontent.com/39558562/40537956-e4a188ce-602d-11e8-829c-34afa66dfdba.png)

During the upload I specified the path of this xml file. See the screen shot below:

![image](https://user-images.githubusercontent.com/39558562/40538068-3cf75d6e-602e-11e8-9fb6-f1dfcc05219f.png)


I still get the same error. Am I missing anything? Please help

**Comment by rferraton** [comment]
Try to remove "projects" from the target url

**Comment by rferraton** [comment]
Tableau Version ?

**Comment by sdasgupta-18** [comment]
It's 10.5.0

**Comment by piyum24** [comment]
Any update/resolution for this? I also wasn't able to get the .XML file to work either for .TWB files with Live connections or .TWBX files with no embedded data source credentials.

**Comment by gbeaver** [comment]
@rferraton  @sdasgupta-18 , Has there been any resolution to the reported issue? I have a similar issue I would love to fix!

Live Connection from .twb

Tableau version 10.5.3

**Comment by piyum24** [comment]
Gbeaver, I wasn't able to resolve the issue (it wasn't worth investing more time in). For .TWB files, I recommend you have the owners embed the authentication credentials and/or switch them to extracts, so you're dealing with .TWBX files. Not a great answer, but it worked for us.

**Comment by gbeaver** [comment]
Thanks @piyum24 unfortuantely that is not an option for me :(

I'm hoping the others may have some insight!

**Comment by rferraton** [comment]
Did you try with my fork for tableau 10.5 ? https://github.com/aetperf/TabMigrate/tree/10.5-dev/TabRESTMigrate/bin/Release

**Comment by piyum24** [comment]
@rferraton, is Tabmigrate v10.5 branch compatible with updated Tableau versions (e.g. 2018.3)? If not, 
 are there any plans for updating Tabmigrate from this v10.5 to v2018.3? 

Appreciate the help maintaining this open-source tool.

**Comment by rferraton** [comment]
> @rferraton, is Tabmigrate v10.5 branch compatible with updated Tableau versions (e.g. 2018.3)? If not,
> are there any plans for updating Tabmigrate from this v10.5 to v2018.3?
> 
> Appreciate the help maintaining this open-source tool.

new branch for 2018.3 with a release : https://github.com/aetperf/TabMigrate/blob/2018.3-dev/TabRESTMigrate/bin/Release/TabRESTMigrate.exe

**Comment by piyum24** [comment]
Thanks @rferraton! I'll test it out.

**Comment by srikanth999** [comment]
Thanks @rferraton. I ran this and notice an error while generating the .twb

Error generating Twb file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\XXXXX\Tableau\Tabmigrate\_SampleFiles\SiteInventory.twb'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Threading.CompressedStack.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at TwbReplaceCSVReference.Execute()
   at TaskMaster.Execute_GenerateSiteInventoryFile_Twb(String pathReportCsv)
