### ISSUE TITLE
Errors logging into test and prod servers from TabMigrate

### ISSUE THREAD

**Issue by tomink1210** [tableau/TabMigrate#52]
We have 2 Tableau Servers hosted in Azure. Both have TabMigrate (TM) installed but I can't log into either server from TM. 

Errors are different:
TEST - Error returned from sign in response: System.Net.WebException: The remote server returned an error: (404) Not Found.
PROD - Error: Error returned from sign in response: System.Net.WebException: The remote server returned an error: (401) Unauthorized.

Both have recently been upgraded to 2020.2. I have previously tested TM with the test server and it seemed to work. Not sure what URL I used but I don't believe anything else has changed. Any ideas gratefully received!

**Comment by Rakshith-Gowda** [comment]
My Dev server is on 2020.4.1 however, the prod server is on  2020.1.7. TabMigrate v1.16 works on dev server but it doesn't on prod. 
The error that I see when tried to connect to the prod server is as follows:
Error: Error returned from sign in response: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at TableauServerSignIn.ExecuteRequest()

I am assuming that it is similar to what's mentioned above.
