### ISSUE TITLE
Does this tool work for SAML Authentication

### ISSUE THREAD

**Issue by rajimishra** [tableau/TabMigrate#61]
I have tried using SAML authentication to login but it doesnt work. Can someone suggest if it can be used if we have SAML Authentication as i am getting error
000,  3/14/2022 3:43:25 PM, Error: Error returned from sign in response: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at TableauServerSignIn.ExecuteRequest()

**Comment by ardalanafkhami** [comment]
You may want to use a token access to get around SAML authentication. 
These two articles should help you understand how tokens work and how to create a token.
https://help.tableau.com/current/server/en-us/security_personal_access_tokens.htm
https://help.tableau.com/current/pro/desktop/en-us/useracct.htm#create-and-revoke-personal-access-tokens
